apiVersion: lib.projectsveltos.io/v1alpha1
kind: HealthCheck
metadata:
 name: depl-replicas
spec:
 group: apps
 version: v1
 kind: Deployment
 script: |
   function evaluate()
     hs = {}
     hs.status = "Progressing"
     hs.message = ""
     if obj.status ~= nil then
       if obj.status.availableReplicas ~= nil then
         if obj.status.availableReplicas == obj.spec.replicas then
           hs.status = "Healthy"
         end
         if obj.status.availableReplicas ~= obj.spec.replicas then
           hs.status = "Progressing"
           hs.message = "expected replicas: " .. obj.spec.replicas .. " available: " .. obj.status.availableReplicas
         end
       end
       if obj.status.unavailableReplicas ~= nil then
         if obj.status.unavailableReplicas ~= 0 then
           hs.status = "Degraded"
           hs.message = "replicas are unavailable"
         end
       end
     end
     return hs
   end