apiVersion: lib.projectsveltos.io/v1alpha1
kind: Classifier
metadata:
  name: small-ns
spec:
  classifierLabels:
  - key: ns
    value: small
  deployedResourceConstraints:
  - group: ""
    version: v1
    kind: Namespace
    minCount: 6
    maxCount: 8
    script: |
      function evaluate()
       hs = {}
       hs.matching = false
       hs.message = ""
       if obj.metadata.labels ~= nil then
         for key, value in pairs(obj.metadata.labels) do
           if key == "sveltos" then
             if value == "fv" then
               hs.matching = true
             end
           end
         end
       end
       return hs
      end